### ISSUE TITLE
Fix: _layouts.camps

### ISSUE THREAD

**Issue by Jubeki** [CodeDesignInitiative/campy-web#14]
Right under FAQ is the timetable and in the column right is a formular.
Wouldn't it be better if FAQ and the formular are columns and the timetable is on full width?
Then there wouln't be too much white space on right side of the page.

Also there is a problem with "Düsseldorf". The camp is only three days long but the timetable is for four days. For me it is a little bit confusing.

**Comment by minthemiddle** [comment]
These are actually two separate issues. I will create a new one for "Timetable does not fit camps that do not last 4 days."
