### ISSUE TITLE
Add: ssl and redirect to code.design/camps from code.camp

### ISSUE THREAD

**Issue by fronbasal** [CodeDesignInitiative/campy-web#141]
# What did you expect?
HTTPS at code.camp.

# What did you get instead?
No HTTPS at code.camp.

# What were your exact steps to get to your problem?
Browse to code.camp.

**Comment by toorusr** [comment]
Also there should be a redirect to the code.design/camps page

**Comment by fronbasal** [comment]
Great idea.
