### ISSUE TITLE
Bug: Timetable does not fit camps that do not last 4 days

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/campy-web#15]
There are camps that don't last 4 days, e.g. "Düsseldorf". The timetable in `_layouts/camp` is for four days. That is wrong. There need to be individual timetables for shorter or longer events.

**Comment by minthemiddle** [comment]
No, not a rare case. We will soon announce a 5-day camp.

**Comment by toorusr** [comment]
Oh, well, thats cool.

**Comment by Jubeki** [comment]
How about a yield that if it is empty just shows the standard text and else the content from the markdown file (section: content)? So the text could be easily edited for camps with three, five or more days.
