### ISSUE TITLE
Fix: Show patrons and sponsors section only if has partners

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/campy-web#20]
Right now the camp sections patrons and sponsors are shown even if there none in one sectiion.

They should be filtered out if no partner exists for a camp:

Example https://code.design/camps/berlin/1710/ :

<img width="747" alt="screen shot 2018-02-22 at 14 24 04" src="https://user-images.githubusercontent.com/1950766/36540807-0e05d9da-17dc-11e8-91e7-9827bf273c88.png">

**Comment by Jubeki** [comment]
You could simply use the $Collection->Count()  function and check if it is empty or not. i don't know if it work together with the filter
